### ISSUE TITLE
Images Display Only After Search

### ISSUE THREAD

**Issue by allcentury** [commercetools/commercetools-ios-sdk#124]
Perhaps an issue with our project configuration but for project `winecom-stage`, we're not seeing images on the initial product list view:

![img](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/16427/1987491/xoYIWjAkMwzU2cG/upload.png)

However once we do a product search, they show:

![img](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/16427/1987491/bqmXW0ECNAAW938/upload.png)

**Comment by nikola-mladenovic** [comment]
@allcentury - if you look at the image URLs you'll notice that one of the URLs from the initial product screen is `http://cache.wine.com/labels/132287h.jpg`, and for the _Enkidu_ results `https://63ee226c73945aa59e27-c7e325d6189b754faa0a86a6848c5737.ssl.cf1.rackcdn.com/img-iqhsxkCy.jpg`.

The images served over HTTP cannot be loaded due to ATS limitation (https://developer.apple.com/news/?id=12212016b).

**Comment by allcentury** [comment]
Thanks @nikola-mladenovic - looks like our importer script missed a few.
