### ISSUE TITLE
How to get notified of tokenState request completion?

### ISSUE THREAD

**Issue by kornerr** [commercetools/commercetools-ios-sdk#159]
Hi.

Performing `Commercetools.config = configuration` results in either immediate `Commercetools.authState` change, or a delayed one because request is made to Commercetools API. There's no completion handler to know when that potential request succeeded. So there's no way to know if/when `anonymousToken` has been established.

How to get notified of tokenState request completion?

**Comment by nikola-mladenovic** [comment]
Currently there's no way to get notified when the `tokenState` changes.

After setting the `Commercetools.config`, it's guaranteed that the next method / endpoint you invoke will respect the newly project / configuration.

That means you don't have to wait for the `authState` change to happen in order to make some actions / queries (e.g retrieve an active cart). You can just do something like this:
```swift
Commercetools.config = configuration
Cart.active { result in
    if let cart = result.model, result.isSuccess {
        // do something with the cart
    }
}
```

However, I do think it would be handy to have notifications being posted on `authState` change, so I'll probably make that improvement in the next release.

**Comment by kornerr** [comment]
> After setting the Commercetools.config, it's guaranteed that the next method / endpoint you invoke will respect the newly project / configuration.

Oh, good to know this. You should really put this line into README because that was my concern exactly.

Thanks.

**Comment by nikola-mladenovic** [comment]
Valid point @kornerr - will make sure that gets into README 👍
