### ISSUE TITLE
Support for external OAuth tokens

### ISSUE THREAD

**Issue by skyriakou** [commercetools/commercetools-ios-sdk#172]
In order to support using [external OAuth tokens](https://docs.commercetools.com/http-api-authorization#requesting-an-access-token-using-an-external-oauth-server-beta), the SDK needs to be updated, so that the client application using the SDK can specify the token to be used in the `Authorization` headers.

Once a token is set by the client, it should be used in all subsequent requests to platform API. It should not be used for auth requests.

After a token is unset by the client, the SDK will either obtain new anonymous session token or plain token, depending on the configuration applied.

Open items:
- After the token is set by the client, should we allow `me/signup` and `me/login`?
@cneijenhuis would like to hear your thoughts on this.

**Comment by cneijenhuis** [comment]
We have plans to touch the whole customer endpoint to make it work properly with external OAuth tokens (e.g. don't require a password, offer an alternative to login that merges anonymous carts etc.). However, these aren't scheduled to be worked on in the near future.

For the SDK, I'd suggest to either not touch those endpoints yet or, if you prefer, disallow them, and otherwise wait until the proper features are in the API.

**Comment by nikola-mladenovic** [comment]
Thank you for the update.

Since the external token will be set by the client on the global SDK level (for all non-auth / platform endpoints), IMHO it'd be best to put `fatalError()` with an appropriate description, in case login or signup methods are called while the external token is being used.

That way, anyone who plays around with this feature would be aware of the current limitation during dev time.
