### ISSUE TITLE
Release on Carthage

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-ios-sdk#20]
Would be great if we could integrate this with Travis, i.e. automatically release when we use `git tag`.

**Comment by nikola-mladenovic** [comment]
Thinking more about supporting Carthage...

Right now we do have one dependency, and that's `Alamofire`. When using CocoaPods for our SDK, it gets automatically pulled, because we have specified the dependency in our `podspecs`.

That also means that we wouldn't be able to support Carthage currently with our project. One possible workaround would be to have Alamofire project included in our repository. But that wouldn't be very clean and nice approach. Also, it might introduce some issues for people using our SDK and Alamofire via CocoaPods at the same time, because we wouldn't be having the dependency in the `podspecs` anymore.
Another ugly workaround would be to try and extract one small subset of functionalities we're using from Alamofire, and incorporate that directly into the SDK project.

But any of these do require time, so suggestion is to leave Carthage support for now.

**Comment by cneijenhuis** [comment]
Okay, let's leave it at that then!
